### ISSUE TITLE
Please change the label on the "Activate" button in "Start / Stop"

### ISSUE THREAD

**Issue by sinistre1973** [metindikbas/msfs-pushback-helper-app#18]
This would be more logical and intuitive in my opinion

**Comment by metindikbas** [comment]
It is easy to write Start/Stop depending on the click count. Initially it shows Start. After first click it shows Stop etc. However, it could be better to read pushback state from simulator to show correct text. Because if you activate pushback without clicking PushBack Helper button, button name will be wrong.

**Comment by alex-johnson** [comment]
#24 will fix this, the UI has been reworked a bit. Not this exact way but it gets rid of the Activate button
